Feat: AT-5181 switch spotinst to use equalAzDistribution
amplify-education/asiaq pull request #390
Opened 2021-09-16 21:28 UTC by cl3086

From the Generous Bear incident, we notice new instances were favoring a specific AZ instead of it being equally distributed across all AZ's. This impacts reliability in a way if an AZ is having issues and instances were being deployed to that AZ. So we are switching Spotinst to equally distribute instances across the AZ's.

2021-09-16 21:42 UTC, skim-amplify approved these changes, later dismissed

2021-09-16 22:52 UTC, jconstance-amplify approved these changes

2021-09-17 13:39 UTC, jconstance-amplify requested changes
Actually, you need a version bump

2021-09-17 13:58 UTC, cl3086 commented
Oh, good catch

2021-09-17 14:01 UTC, jconstance-amplify approved these changes

2021-09-17 14:01 UTC, merged

2021-09-17 14:01 UTC, jconstance-amplify commented
Bit surprised no until test changes

2021-09-17 14:03 UTC, cl3086 commented
Do you mean unit test changes?

2021-09-17 14:08 UTC, jconstance-amplify commented
Yes.

2021-09-17 14:10 UTC, cl3086 commented
That one spot in `tests/unit/test_disco_elastigroup.py` was the only place I found that was checking for `availabilityVsCost`. Also, all the tests passed locally and I think the PR checks were running them too